### ISSUE TITLE
Update to 1.0.18-5

### ISSUE THREAD

**Issue by CondormanFr** [marcelmaatkamp/docker-flightradar24-feeder#1]
Hi,
Is it posible to update to latest version ? 
http://feed.flightradar24.com/linux/fr24feed_1.0.18-5_amd64.tgz

I tried but there is a unresolved dependency to :   
```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./fr24feed) 
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./fr24feed)

```
Thanks

**Comment by marcelmaatkamp** [comment]
Thanks for pointing out the new version number!

**Comment by CondormanFr** [comment]
Thanks for the quick update. It works like a charm.
